### ISSUE TITLE
react-native android app crash 

### ISSUE THREAD

**Issue by aniruddhbhamare** [RobertSasak/react-native-openalpr#93] opened 2020-07-07 10:51 UTC
"react": "16.9.0",
"react-native": "0.61.5",
 "react-native-openalpr": "^2.1.1",
"react-native-permissions": "^2.0.9",

camera open n after 2 - 3 sec. app crashes on android

**Comment by RobertSasak** [comment] 2020-07-07 11:40
Duplicate of this https://github.com/RobertSasak/react-native-openalpr/issues/61 ?

**Comment by waheedshabeer** [comment] 2020-08-04 19:44
please give solution

**Comment by RobertSasak** [comment] 2020-08-05 09:15
Without further information there is nothing to be done.

**Comment by duartejc** [comment] 2020-11-07 20:42
I fixed similar crash issue adding this configuration in _app/build.gradle_ file:

```
android {
    ...
    defaultConfig {
       ...
        ndk { 
            abiFilters "armeabi-v7a" 
        } 
    }
}
```

**Closed** 2021-05-03 08:43 UTC
